name: Bump Web Version

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'

jobs:
  bump-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Bump version and push tag for Web
        uses: phips28/gh-action-bump-version@v9.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: 'web'
          PACKAGE_FILENAME: 'package.json'
        with:
          tag-prefix: 'web-v'
          commit-message: 'ci(web): bump version to {{version}} [skip ci]'